version: "3"
services:
  mentor-server:
    image: localhost:5000/mentor-server-local
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - backend
networks:
  backend: